services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.18.0
    container_name: movie-rec-sys-mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts --serve-artifacts
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_store:/mlflow

  train:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-rec-sys-train
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env.example
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    command: ["dvc", "repro"]
